# Project-local io-mcp config — merged with ~/.config/io-mcp/config.yml
# These options appear at the end of every choice list (silent = not read during intro)

extraOptions:
  - title: Audit io-mcp logs
    description: View the logs via MCP and look for any issues
    silent: true
  - title: Propose next work
    description: Suggest the next 3 most impactful things to work on
    silent: true
  - title: Commit and push
    description: Stage all changes, commit with a descriptive message, and push to the remote
    silent: true
